# Generated by Django 3.2.6 on 2021-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spider',
            name='spider_image',
            field=models.ImageField(default='default.jpg', upload_to='spiders_pics'),
        ),
    ]
